---

# Open edX Native installation for single server community installs.

- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    EDXAPP_PREVIEW_LMS_BASE: '{{ EDXAPP_LMS_BASE }}'
    EDXAPP_LOGIN_REDIRECT_WHITELIST: [ "{{ EDXAPP_CMS_BASE }}" ]
    EDXAPP_LMS_BASE_SCHEME: http
    EDXAPP_LMS_NGINX_PORT: '80'

    ##### Modifications for eduplusca 20200317
    #####
    edx_platform_version: 'master'

    repo_eduplusca: "eduplusca"
    version_eduplusca: "eduplusca-ironwood.master"

    CERTS_REPO: 'https://github.com/{{ repo_eduplusca }}/edx-certificates.git'
    certs_version: "{{ version_eduplusca }}"
    edx_ansible_source_repo: 'https://github.com/{{ repo_eduplusca }}/configuration.git'
    configuration_version: "{{ version_eduplusca }}"
    edx_platform_repo: 'https://github.com/{{ repo_eduplusca }}/edx-platform.git'
    edx_platform_version: "{{ version_eduplusca }}"
    forum_source_repo: 'https://github.com/{{ repo_eduplusca }}/cs_comments_service.git'
    forum_version: "{{ version_eduplusca }}"
    NOTIFIER_SOURCE_REPO: 'https://github.com/{{ repo_eduplusca }}/notifier.git'
    NOTIFIER_VERSION: "{{ version_eduplusca }}"
    xqueue_source_repo: 'https://github.com/{{ repo_eduplusca }}/xqueue.git'
    XQUEUE_VERSION: "{{ version_eduplusca }}"
    #####ECOMMERCE_VERSION: "{{ version_eduplusca }}"
    #####ECOMMERCE_WORKER_VERSION: "{{ version_eduplusca }}"
    DISCOVERY_VERSION: "{{ version_eduplusca }}"
    demo_version: "{{ version_eduplusca }}"
    #####INSIGHTS_VERSION: "{{ version_eduplusca }}"
    #####ANALYTICS_API_VERSION: "{{ version_eduplusca }}"
    #####THEMES_VERSION: "{{ version_eduplusca }}"
    #####
    ##### Modifications for eduplusca 20200317

    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True
    DISCOVERY_URL_ROOT: 'http://localhost:{{ DISCOVERY_NGINX_PORT }}'
    COMMON_ENABLE_AWS_ROLE: false
    ecommerce_create_demo_data: true
    credentials_create_demo_data: true
    SANDBOX_ENABLE_DISCOVERY: true
    SANDBOX_ENABLE_ECOMMERCE: true
    SANDBOX_ENABLE_ANALYTICS_API: true
    SANDBOX_ENABLE_INSIGHTS: true
    SANDBOX_ENABLE_RABBITMQ: true
    JOURNALS_ENABLED: false
  roles:
    - role: swapfile
      SWAPFILE_SIZE: 4GB
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      - forum
      - xqueue
      nginx_default_sites:
      - lms
    - role: edxlocal
      when: EDXAPP_MYSQL_HOST == 'localhost'
    - role: memcache
      when: "'localhost' in ' '.join(EDXAPP_MEMCACHE)"
    - role: mongo_3_2
      when: "'localhost' in EDXAPP_MONGO_HOSTS"
    - role: rabbitmq
      rabbitmq_ip: 127.0.0.1
      when: SANDBOX_ENABLE_RABBITMQ
    - role: edxapp
      celery_worker: True
    - edxapp
    ##### Modifications for eduplusca 20200317
    ##### not installing ecommerce, ecomworker, analytics_api
    ##### not installing insights, edx_notes_api
    #####
    #####- role: ecommerce
    #####  when: SANDBOX_ENABLE_ECOMMERCE
    #####- role: ecomworker
    #####  ECOMMERCE_WORKER_BROKER_HOST: 127.0.0.1
    #####  when: SANDBOX_ENABLE_ECOMMERCE
    #####- role: analytics_api
    #####  when: SANDBOX_ENABLE_ANALYTICS_API
    #####- role: insights
    #####  when: SANDBOX_ENABLE_INSIGHTS
    ##### not ready yet: - edx_notes_api
    #####
    ##### not installing insights, edx_notes_api
    ##### not installing ecommerce, ecomworker, analytics_api
    ##### Modifications for eduplusca 20200317
    - demo
    - oauth_client_setup
    - oraclejdk
    - role: elasticsearch
      when: "'localhost' in EDXAPP_ELASTIC_SEARCH_CONFIG|map(attribute='host')"
    - forum
    - role: discovery
      when: SANDBOX_ENABLE_DISCOVERY
    ##### Modifications for eduplusca 20200317
    ##### not installing journals
    #####
    #####- role: journals
    #####  when: JOURNALS_ENABLED
    #####
    ##### not installing journals
    ##### Modifications for eduplusca 20200317
    - role: notifier
      NOTIFIER_DIGEST_TASK_INTERVAL: 5
    - role: xqueue
      update_users: True
    - certs
    - edx_ansible
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: postfix_queue
      when: POSTFIX_QUEUE_EXTERNAL_SMTP_HOST != ''
    - role: datadog-uninstall
      when: not COMMON_ENABLE_DATADOG
